#!/bin/bash

# ==============================================================================
# QNAP/Ubuntu Stability & Performance Fixer
# ==============================================================================
# Purpose: Fixes system crashes, ZFS checksum errors, and audio driver log spam
#          on QNAP hardware running Ubuntu/Debian.
#
# Changes made:
# 1. Disables PCIe Active State Power Management (ASPM) to prevent storage controller timeouts.
# 2. Blacklists incompatible audio drivers to stop kernel log floods.
# 3. Forces CPU Governor to 'performance' to prevent latency spikes.
# 4. Clears old ZFS error counters.
# ==============================================================================

# USE AT YOUR OWN RISK.


# --- CONFIGURATION VARIABLES ---
# Change 'data' to your actual ZFS pool name
ZFS_POOL_NAME="data"

# --- SAFETY CHECKS ---
if [[ $EUID -ne 0 ]]; then
   echo "Error: This script must be run as root." 
   echo "Try running: sudo $0"
   exit 1
fi

echo "Starting system stabilization fixes..."

# ==============================================================================
# STEP 1: Disable PCIe ASPM (Fixes Storage/ZFS Timeouts)
# ==============================================================================
echo "[1/4] Checking PCIe ASPM settings..."

GRUB_FILE="/etc/default/grub"
if grep -q "pcie_aspm=off" "$GRUB_FILE"; then
    echo "  - ASPM is already disabled in GRUB. Skipping."
else
    echo "  - Disabling ASPM in $GRUB_FILE..."
    # Back up the config first
    cp "$GRUB_FILE" "${GRUB_FILE}.bak"
    
    # Append the flag to the generic line
    sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="/GRUB_CMDLINE_LINUX_DEFAULT="pcie_aspm=off /' "$GRUB_FILE"
    
    echo "  - Updating GRUB..."
    update-grub
    echo "  - Done. (Requires Reboot to take effect)"
fi

# ==============================================================================
# STEP 2: Blacklist Audio Drivers (Fixes dmesg Log Spam)
# ==============================================================================
echo "[2/4] configuring Audio Driver Blacklist..."

BLACKLIST_FILE="/etc/modprobe.d/blacklist-audio.conf"
# We write the file fresh to ensure all problem drivers are caught
cat <<EOF > "$BLACKLIST_FILE"
# Generated by QNAP Stability Script
# Prevents 'dsp core power down' errors and 'snd_hda_intel' crashes
blacklist snd_hda_intel
blacklist snd_sof_pci_intel_icl
blacklist snd_sof_intel_hda_common
EOF

echo "  - Blacklist file created at $BLACKLIST_FILE"
echo "  - Updating initramfs..."
update-initramfs -u > /dev/null
echo "  - Done."

# ==============================================================================
# STEP 3: Optimize CPU Performance (Prevents Latency Spikes)
# ==============================================================================
echo "[3/4] Setting CPU Governor to 'Performance'..."

# Ensure the utility is installed
if ! dpkg -l | grep -q cpufrequtils; then
    echo "  - Installing cpufrequtils..."
    apt-get update -qq && apt-get install -y -qq cpufrequtils
fi

# Configure the default governor
CONFIG_FILE="/etc/default/cpufrequtils"
if grep -q 'GOVERNOR="performance"' "$CONFIG_FILE" 2>/dev/null; then
    echo "  - CPU Governor already set to performance."
else
    echo 'GOVERNOR="performance"' > "$CONFIG_FILE"
    echo "  - Configuration updated."
    # Restart service to apply immediately
    systemctl restart cpufrequtils
    echo "  - Service restarted."
fi

# ==============================================================================
# STEP 4: ZFS Cleanup (Optional)
# ==============================================================================
echo "[4/4] Checking ZFS Pool status..."

if command -v zpool &> /dev/null; then
    # Check if the pool exists
    if zpool list "$ZFS_POOL_NAME" &> /dev/null; then
        # Check if the pool has errors recorded
        if zpool status "$ZFS_POOL_NAME" | grep -q "One or more devices has experienced an unrecoverable error"; then
            echo "  - Detected old errors on pool '$ZFS_POOL_NAME'. Clearing..."
            zpool clear "$ZFS_POOL_NAME"
            echo "  - Pool errors cleared."
        else
            echo "  - No errors found on pool '$ZFS_POOL_NAME'. Skipping clear."
        fi
    else
        echo "  - Pool '$ZFS_POOL_NAME' not found. Skipping."
    fi
else
    echo "  - ZFS not installed. Skipping."
fi

echo "=============================================================================="
echo "All tasks complete!" 
echo "Please REBOOT your system to ensure all kernel parameters apply."
echo "=============================================================================="
